keywords:
  - "2D transition metal oxide heterostructure"
  - "two-dimensional transition metal oxide heterostructure"
- "2D TMO heterostructure"
time:
  start: 2015
  end: 2025
document_type:
  - Article
  - Review
database: Web of Science
